# Generated by Django 3.2 on 2021-05-17 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import item_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[item_app.models.checkRating])),
                ('name', models.CharField(max_length=40)),
                ('project_type', models.CharField(max_length=35)),
                ('keyword_list', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=80)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(help_text='Ex: Started, In Progress or Completed', max_length=15)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ImageField(default='project_default_pic.png', upload_to='project_images')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
